In [20]:
import numpy as np
a = np.random.randint(low=1,high=5,size=5)
b = np.random.randint(low=1,high=5,size=5)
l = np.random.uniform(low=0,high=1,size=5)
c = a*l+b*(1-l)
print(a)
print(b)
print(l)
print(c)
d = np.append(a,b)
print(d)
print(d[0:2])



[1 1 3 4 2]
[2 3 2 1 4]
[0.3692991  0.10345844 0.81281325 0.29984231 0.39696313]
[1.6307009  2.79308312 2.81281325 1.89952692 3.20607374]
[1 1 3 4 2 2 3 2 1 4]
[1 4 3]
