In [3]:
import numpy as np
a = np.random.randint(low=1,high=5,size=5)
b = np.random.randint(low=1,high=5,size=5)
l = np.random.uniform(low=0,high=1,size=5)
c = a*l+b*(1-l)
print(a)
print(b)
print(l)
print(c)
d = np.append(a,b)
print(d)
print(d[0:2])
k = np.random.randint(low=1,high=2,size=5)
print(k)
g = np.array([5,10,5])
g = g/g.sum()
print(g)
print(np.power(3,2))

[3 1 1 3 1]
[1 2 2 3 3]
[0.45233512 0.52983118 0.15486748 0.03756113 0.20022644]
[1.90467024 1.47016882 1.84513252 3.         2.59954712]
[3 1 1 3 1 1 2 2 3 3]
[3 1]
[1 1 1 1 1]
[0.25 0.5  0.25]
